//
// This file was generated by the JPA Modeler
//
package entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

@Entity
@Table(name = "cargo")
public class Cargo implements Serializable {

    @Column(name = "idCargo", table = "cargo", nullable = false, length = 50)
    @Id
    @FormParam("idCargo")
    private String idCargo;

    @Column(name = "descripcion_Cargo", table = "cargo", length = 45)
    @Basic
    @FormParam("descripcionCargo")
    private String descripcionCargo;

    @Column(name = "estado", table = "cargo", length = 45)
    @Basic
    @FormParam("estado")
    private String estado;

    public Cargo() {

    }

    public String getIdCargo() {
        return this.idCargo;
    }

    public void setIdCargo(String idCargo) {
        this.idCargo = idCargo;
    }

    public String getDescripcionCargo() {
        return this.descripcionCargo;
    }

    public void setDescripcionCargo(String descripcionCargo) {
        this.descripcionCargo = descripcionCargo;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }
}
